description = 'Smart Pet Feeder'
ext.details = 'Driver to connect to custom built smart cat feeder.'

dependencies {
    // OSH core
    implementation 'org.sensorhub:sensorhub-core:' + oshCoreVersion

    // MQTT client — Eclipse Paho
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
}

osgi {
    manifest{
        attributes('Bundle-Vender': 'GeoRobotix Innovative Research')
        attributes('Bundle-Activator': 'org.sensorhub.impl.sensor.petfeeder.Activator')
    }
}

// add info to maven pom
ext.pom >>= {
  developers {
    developer {
      id 'drewbotts'
      name 'Drew Botts'
      organization 'GeoRobotix Innovative Research'
      organizationUrl 'http://www.georobotix.us' 
    }
  }
}
